- name: "Copy deployment check script"
  copy:
    src: "check_deployment.sh"
    dest: "/root/check_deployment.sh"
    mode: "0755"

- name: Create a k8s namespace
  kubernetes.core.k8s:
    name: "{{item}}"
    api_version: v1
    kind: Namespace
    state: present
  with_items:
    - ingress-nginx
    - supabase-app

- name: Cleanup previously cloned repository
  ansible.builtin.file:
    path: /root/supabase/supabase_backend
    state: absent


# - name: Clone Sandbox Backend Deployment Repo
#   ansible.builtin.git:
#     repo: https://github.com/oci-sunbird/sandbox-usecase-supabase-backend.git
#     dest: /root/supabase/supabase_backend
#     single_branch: yes
#     version: customized_backend

- name: Deploy service monitors
  shell: kubectl apply -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml

- name: Add a metrics-server helm repository
  kubernetes.core.helm_repository:
    name: metrics-server
    repo_url: https://kubernetes-sigs.github.io/metrics-server/

- name: Add a certmanager helm repository
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io

- name: Add a ACME webhook for Oracle Cloud Infrastructure helm repository
  kubernetes.core.helm_repository:
    name: cert-manager-webhook-oci
    repo_url: https://dn13.gitlab.io/cert-manager-webhook-oci


- name: Create project directories
  file:
    path: "{{item}}"
    state: directory
    mode: '0755'
  with_items:
    - /root/supabase
    - /root/supabase/github
    - /root/supabase/tls
    - /root/proj_supabase/customization
    - /root/proj_supabase/customization/cert-manager

- name: Install metrics-server
  kubernetes.core.helm:
    name: metrics-server
    chart_ref: metrics-server/metrics-server
    release_namespace: monitoring
    create_namespace: true
    update_repo_cache: true