- name: Check if jwt_anonKey and jwt_serviceKey are empty
  command: echo
  register: jwt_keys_check

- name: Copy the JWT generation script to the target machine
  template:
    src: generate_jwt_keys.j2
    dest: /tmp/generate_jwt_keys.sh
    mode: '0755'

- name: Run the JWT generation script if keys are empty
  shell: /tmp/generate_jwt_keys.sh
  register: jwt_keys_output
  when: jwt_keys_check.stdout.find('jwt_anonKey') == -1 or jwt_keys_check.stdout.find('jwt_serviceKey') == -1

- name: Parse the generated keys and set facts
  set_fact:
    jwt_anonKey: "{{ jwt_keys_output.stdout_lines | select('search', 'jwt_anonKey') | first | regex_replace('jwt_anonKey=', '') }}"
    jwt_serviceKey: "{{ jwt_keys_output.stdout_lines | select('search', 'jwt_serviceKey') | first | regex_replace('jwt_serviceKey=', '') }}"
  when: jwt_keys_output is defined

- name: Debug the generated keys
  debug:
    msg:
      - "jwt_anonKey: {{ jwt_anonKey }}"
      - "jwt_serviceKey: {{ jwt_serviceKey }}"
      
- name: Clone Supabase Kubernetes repository
  git:
    repo: https://github.com/supabase-community/supabase-kubernetes
    dest: /root/supabase/github

- name: Change to the charts directory
  shell: |
    cd /root/supabase/github/charts/supabase && pwd
  register: supabase_chart_dir
  changed_when: false

- name: Define supabase helm values.yaml for deployment
  template:
    src: "values.oke.yaml.j2"
    dest: "/root/supabase/values.oke.yaml"
    mode: '0755'

- name: Install the Helm chart
  shell: |
    cd /root/supabase/github/charts/supabase
    helm install {{ supabase_namespace }} -n {{ supabase_namespace }} -f /root/supabase/values.oke.yaml .
  args:
    chdir: "/root/supabase/github/charts/supabase"

