- name: Install certmanager
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    release_namespace: cert-manager
    create_namespace: true
    update_repo_cache: true
    values:
      installCRDs: true

- name: Install cert-manager-webhook-oci
  kubernetes.core.helm:
    name: cert-manager-webhook-oci
    chart_ref: cert-manager-webhook-oci/cert-manager-webhook-oci
    release_namespace: cert-manager
    create_namespace: true
    update_repo_cache: true


- name: Get oci iam user api private key
  slurp:
    src: /root/.oci/bastion.key
  register: api_private_key

- name: Set client_assertion_jwk private key
  set_fact:
    bastion_user_api_key: "{{api_private_key.content | b64decode}}"

- name: "Update templates"
  template:
    src: "cert-manager/{{item}}.j2"
    dest: "/root/proj_supabase/customization/cert-manager/{{item}}"
    mode: '0755'
  with_items:
    - oci-webhook-profile.yaml
    - clusterissuer.yaml
    - certificate.yaml

- name: Create k8s objects for certmanager
  kubernetes.core.k8s:
    state: present
    src: /root/proj_supabase/customization/cert-manager/{{item}}
  with_items:
    - oci-webhook-profile.yaml
    - clusterissuer.yaml
    - certificate.yaml