
# The tasks folder is where the actual automation steps of the role are defined.
# The main.yaml file within tasks is typically the primary entry point for the tasks the role will execute.
# Contains specific Ansible modules and commands to perform actions, such as deploying software, configuring services, or managing infrastructure resources.
# If additional task files are needed for modularity or organization, they can be included from main.yaml to structure the workflow better.

- include_tasks: common.yaml
#- include_tasks: install_certmanager.yaml
- include_tasks: install_nginx_controller.yaml
#- include_tasks: update_zone_record.yaml
- include_tasks: install_supabase.yaml