- hosts: bastion
  become: true
  environment:
    KUBECONFIG: "/root/.kube/oke_k8s_config"
  roles:
    - supabase.iac.bastion_common
    - supabase.iac.oke_common
    - supabase.iac.supabase_deploy
